
package TPI_Empleados;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Date;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

public class PantallaEmpleado extends javax.swing.JFrame {

    //Variables
    private Empleados emple;
    private DatabaseConection c;
    
   //Creo un metodo para que la imagen se adapte al tamaño del boton
    public Icon setIcono(String url, JButton boton){
        
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        
        return icono;
    }
    
    //Constructor
    public PantallaEmpleado() throws ParseException {
        
        initComponents();
        //llamo al metodo que desactiva las cajas
        desactivarCajasBtn();
        txtLegajo.requestFocus(true);
        emple = new Empleados();
        //llamo al metodo setIcono: que me devuelve la imagen icono adapatada al tamaño del boton
        btnBuscar.setIcon(setIcono("/Imagenes/Buscar.png",btnBuscar));
        btnAgregar.setIcon(setIcono("/Imagenes/Agregar.png",btnAgregar));
        
        //coloco un titulo al jFrame
         this.setTitle("Empleados");
         
        //para que el formulario parezca en el centro
        this.setLocationRelativeTo(null);
        
        //desactiva el boton maximizar
        this.setResizable(false);
        
        //   this.mostrarTabla();
    }
   
    
    //Metodo desactivar cajas de texto y bones
    public void desactivarCajasBtn(){
        
     txtApellido.setEnabled(false);
     txtNombre.setEnabled(false);
     txtDNI2.setEnabled(false);
     txtFechaNac.setEnabled(false);
     chkMasculino.setEnabled(false);
     chkFemenino.setEnabled(false);
     chkOtro.setEnabled(false);
     cboCargo.setSelectedItem("**Seleccione Opción**");
     cboCargo.setEnabled(false);
     txtSueldoBruto.setEnabled(false);
     
     btnGuardar.setEnabled(false);
     btnModificar.setEnabled(false);
     btnEliminar.setEnabled(false);
    
    }
    
      //Metodo activar cajas de texto y bones
    public void activarCajas(){
        
        
     txtApellido.setEnabled(true);
     txtNombre.setEnabled(true);
     txtDNI2.setEnabled(true);
     txtFechaNac.setEnabled(true);
     chkMasculino.setEnabled(true);
     chkFemenino.setEnabled(true);
     chkOtro.setEnabled(true);
     cboCargo.setSelectedItem("**Seleccione Opción**");
     cboCargo.setEnabled(true);
     txtSueldoBruto.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLegajo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblSueldoBruto = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        chkMasculino = new javax.swing.JCheckBox();
        chkFemenino = new javax.swing.JCheckBox();
        chkOtro = new javax.swing.JCheckBox();
        cboCargo = new javax.swing.JComboBox<>();
        txtSueldoBruto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblTituloEmpleado = new javax.swing.JLabel();
        txtDNI2 = new javax.swing.JFormattedTextField();
        txtFechaNac = new javax.swing.JFormattedTextField();
        lblFondoEmple = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLegajo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLegajo.setText("Legajo:");
        getContentPane().add(lblLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 50, 30));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNombre.setText("Apellido:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 60, 30));

        lblApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblApellido.setText("Nombre:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 145, -1, 20));

        lblFechaNac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFechaNac.setText("Fecha Nacimiento:");
        getContentPane().add(lblFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        lblDNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDNI.setText("DNI:");
        getContentPane().add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 185, -1, 20));

        lblGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGenero.setText("Género:");
        getContentPane().add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        lblCargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCargo.setText("Cargo:");
        getContentPane().add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, 20));

        lblSueldoBruto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSueldoBruto.setText("Sueldo Bruto:");
        getContentPane().add(lblSueldoBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, 30));

        txtLegajo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLegajoActionPerformed(evt);
            }
        });
        txtLegajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLegajoKeyTyped(evt);
            }
        });
        getContentPane().add(txtLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 90, 30));

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 210, 30));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 210, 30));

        chkMasculino.setText("Masculino");
        chkMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(chkMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 263, -1, 30));

        chkFemenino.setText("Femenino");
        chkFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFemeninoActionPerformed(evt);
            }
        });
        getContentPane().add(chkFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 263, 80, 30));

        chkOtro.setText("Otro");
        chkOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOtroActionPerformed(evt);
            }
        });
        getContentPane().add(chkOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 263, 60, 30));

        cboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "**Seleccione Opción**", "Gerente", "Administración", "Contabilidad", "Recursos Humanos", "Secretaria/o", "Personal Cajero", "Personal Repositor", "Personal Limpieza" }));
        getContentPane().add(cboCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 210, 30));

        txtSueldoBruto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSueldoBruto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoBrutoKeyTyped(evt);
            }
        });
        getContentPane().add(txtSueldoBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 210, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setOpaque(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 30, 30));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Microsoft JhengHei", 1, 11)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setOpaque(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 80, 30));

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 11)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(null);
        btnModificar.setOpaque(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 80, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 11)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setOpaque(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 80, 30));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 11)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(null);
        btnGuardar.setOpaque(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 80, 30));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 11)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setOpaque(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 80, 30));

        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 30, 30));

        lblTituloEmpleado.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 26)); // NOI18N
        lblTituloEmpleado.setForeground(new java.awt.Color(255, 204, 153));
        lblTituloEmpleado.setText("FORMULARIO EMPLEADO");
        getContentPane().add(lblTituloEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 50));

        try {
            txtDNI2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDNI2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNI2FocusLost(evt);
            }
        });
        txtDNI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNI2KeyTyped(evt);
            }
        });
        getContentPane().add(txtDNI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 210, 30));

        try {
            txtFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 90, 30));

        lblFondoEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoEmple.jpg"))); // NOI18N
        getContentPane().add(lblFondoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        //limpiar cajas
        limpiarCajas();
        //metodo que activas las cajas
        activarCajas();
        txtLegajo.setEnabled(false);
        txtApellido.requestFocus(true);
        
        //activo/desactivo botones
         btnGuardar.setEnabled(true);
         btnModificar.setEnabled(false);
         btnEliminar.setEnabled(false);
         btnBuscar.setEnabled(false);
         btnAgregar.setEnabled(false);
         
         //creo el objeto DatabaseConection
         c = new DatabaseConection();
         //se conecta a la BD
            try {
                c.getConectar();
            } catch (SQLException ex) {
                Logger.getLogger(PantallaAltaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            
             //llamo al metodo que me muestra en la caja de texto el valor del proximo legajo
             Empleados emp = c.getLegajoIncremental();
            
             //asigno cada valor obtenido de la BD a las cajas de textos
             txtLegajo.setText(String.valueOf(emp.getLegajo()));
             txtApellido.requestFocus(true);
            
             c.Cerrar();
    }//GEN-LAST:event_btnAgregarActionPerformed
//metodo limpiar cajas
   public void limpiarCajas(){
       
     txtLegajo.setText("");
     txtApellido.setText("");
     txtNombre.setText("");
     txtDNI2.setText("");
     txtFechaNac.setText("");
     chkMasculino.setSelected(false);
     chkFemenino.setSelected(false);
     chkOtro.setSelected(false);
     cboCargo.setSelectedItem("**Seleccione Opción**");
     txtSueldoBruto.setText("");
    
   }
    
    
    private void chkMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMasculinoActionPerformed
      //Cuando haga clic en MASCULINO que los demas checkbox queden destildados
        chkFemenino.setSelected(false);
        chkOtro.setSelected(false);
        
    }//GEN-LAST:event_chkMasculinoActionPerformed

    private void chkFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFemeninoActionPerformed
        //Cuando haga clic en FEMENINO que los demas checkbox queden destildados
        chkMasculino.setSelected(false);
        chkOtro.setSelected(false);
    }//GEN-LAST:event_chkFemeninoActionPerformed

    private void chkOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOtroActionPerformed
        //Cuando haga clic en OTRO que los demas checkbox queden destildados
        chkFemenino.setSelected(false);
        chkMasculino.setSelected(false);
    }//GEN-LAST:event_chkOtroActionPerformed

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //variables - Obtengo lo ingresado por teclado
    	try{
             String apellido = txtApellido.getText();
             String nombre = txtNombre.getText();
             //obtengo el valor del DNI
             Integer dni = Integer.parseInt(txtDNI2.getText());
             String fechaNac  =  txtFechaNac.getText();
            //Obtengo el valor de Genero
            String genero;
            if(chkMasculino.isSelected()) //retorna TRUE si el boton esta seleccionado
              { genero ="Masculino";}
            else 
                if(chkFemenino.isSelected())
                    {genero = "Femenino";}
                else
                      if(chkOtro.isSelected())
                         {genero = "Otro";}
                      else { genero = "";}
            //Obtengo el valor del Cargo
            String cargo =  cboCargo.getSelectedItem().toString();
            //Obtengo el valor del Sueldo
            double sueldoBruto = Double.parseDouble(txtSueldoBruto.getText());
            //------------------------------------------------------------------------------------------------//
            //llamo al metodo ValidarDatos de mi Clase Empleados y le asigno una variable
            boolean setearDatos = emple.ValidarDatos(apellido, nombre, dni, fechaNac, genero, cargo, sueldoBruto);
            
            if(setearDatos == false){ //si retorna FALSE indica que TODOS los datos fueron ingresados correctamente
                
                //llama al metodo validar que el DNI no exista en la BD
                String sql = "SELECT dni FROM Empleados WHERE dni = '" + dni+ "'";
                boolean validarExistDNI = emple.validarDNIExist(dni,sql, null);
                
                if(validarExistDNI == false){// si el DNI ingresado no existe en la BD
                //llamo al metodo INSERTAR EMPLEADOS de mi Clase Empleados
                boolean insertEmple = emple.insertarEmpleados(apellido, nombre, dni, fechaNac, genero, cargo, sueldoBruto);
                if(insertEmple == true){
                    limpiarCajas();
                    txtLegajo.setEnabled(true);
                    txtLegajo.requestFocus(true);
                    desactivarCajasBtn();

                    btnBuscar.setEnabled(true);
                    btnAgregar.setEnabled(true);
                }
              }  else {txtDNI2.setText("");
                       txtDNI2.requestFocus(true);
                      }
            } 

    	} 
        catch(NumberFormatException ex){ //si lo que se ingresa x teclado no es un nro. genera error!
              JOptionPane.showMessageDialog(this, "Faltan datos de Cargar!!","Validación Carga de Datos",JOptionPane.ERROR_MESSAGE); 
              }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String leg = txtLegajo.getText();
        txtLegajo.setEnabled(false);
        btnBuscar.setEnabled(false);
        
        try{
            if(!leg.trim().equals("")){
                            
         //activo/desactivo botones
         btnCancelar.setEnabled(true);
         btnModificar.setEnabled(true);
         btnAgregar.setEnabled(false);
         btnGuardar.setEnabled(false);
         btnEliminar.setEnabled(true); 
         
         //activa las cajas de texto
         activarCajas();

            //obtengo el valor de la caja de texto legajo
            int legajo = Integer.parseInt(this.txtLegajo.getText());

             //creo el objeto DatabaseConection
             c = new DatabaseConection();
             //se conecta a la BD
                try {
                    c.getConectar();
                } catch (SQLException ex) {
                    Logger.getLogger(PantallaAltaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        //llamo al metodo que me retorno el empleado segun legajo ingresado
        Empleados emp = c.getEmpleado(legajo);
        
        if(emp != null){//si NO se genera un error
            
        //asigno cada valor obtenido de la BD a las cajas de textos
        txtLegajo.setText(String.valueOf(emp.getLegajo()));
        txtApellido.setText(emp.getApellido());
        txtNombre.setText(emp.getNombre());
        txtDNI2.setText(String.valueOf(emp.getDni()));
        txtFechaNac.setText(emp.getFechaNac());
        //genero
        if( "Masculino".equals(emp.getGenero())){
            chkMasculino.setSelected(true);
            chkFemenino.setSelected(false);
            chkOtro.setSelected(false);
        }else
             if("Femenino".equals(emp.getGenero())){
                 chkMasculino.setSelected(false);
                 chkFemenino.setSelected(true);
                 chkOtro.setSelected(false);
             } else {chkMasculino.setSelected(false);
                     chkFemenino.setSelected(false);
                     chkOtro.setSelected(true);
                    }
        //cargo
        cboCargo.setSelectedItem(emp.getCargo());
        //Sueldo Bruto
        txtSueldoBruto.setText(String.valueOf(emp.getMontoBruto()));
          
        //desconectar de la BD
        c.Cerrar();
        }//fin del IF(emp != null)
        else{//si el medoto getEmpleado genera error
                limpiarCajas();
                txtLegajo.setEnabled(true);
                txtLegajo.requestFocus(true);
                desactivarCajasBtn();

                btnBuscar.setEnabled(true);
                btnAgregar.setEnabled(true);
             }
        
       }else {JOptionPane.showMessageDialog(null, "No se ingresó el Legajo a Buscar","Validación Carga de Datos",JOptionPane.ERROR_MESSAGE);
                limpiarCajas();
                txtLegajo.setEnabled(true);
                txtLegajo.requestFocus(true);
                desactivarCajasBtn();

                btnBuscar.setEnabled(true);
                btnAgregar.setEnabled(true);
              }
        }catch(NumberFormatException ex){ //si lo que se ingresa x teclado no es un nro. genera error!
              JOptionPane.showMessageDialog(this, "Datos Incorrectos!!! El Legajo ingresado sólo puede contener nros.","Validación Carga de Datos",JOptionPane.ERROR_MESSAGE); 
              txtLegajo.requestFocus(true);
              txtLegajo.setText("");
              desactivarCajasBtn();
              }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        limpiarCajas();
        txtLegajo.setEnabled(true);
        txtLegajo.requestFocus(true);
        desactivarCajasBtn();
        
         btnBuscar.setEnabled(true);
         btnAgregar.setEnabled(true);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLegajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLegajoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       
        //variables - Obtengo lo ingresado por teclado
    	try{
             Integer legajo = Integer.parseInt(txtLegajo.getText());
             String apellido = txtApellido.getText();
             String nombre = txtNombre.getText();
             //obtengo el valor del DNI
             Integer dni = Integer.parseInt(txtDNI2.getText());
             String fechaNac  =  txtFechaNac.getText();
            //Obtengo el valor de Genero
            String genero;
            if(chkMasculino.isSelected()) //retorna TRUE si el boton esta seleccionado
              { genero ="Masculino";}
            else 
                if(chkFemenino.isSelected())
                    {genero = "Femenino";}
                else
                      if(chkOtro.isSelected())
                         {genero = "Otro";}
                      else { genero = "";}
            //Obtengo el valor del Cargo
            String cargo =  cboCargo.getSelectedItem().toString();
            System.out.println("valor del cargo: " + cargo);
            //Obtengo el valor del Sueldo
            double sueldoBruto = Double.parseDouble(txtSueldoBruto.getText());
        //------------------------------------------------------------------------------------------------//
        //llamo al metodo ValidarDatos de mi Clase Empleados y le asigno una variable
        boolean setearDatos = emple.ValidarDatos(apellido, nombre, dni, fechaNac, genero, cargo, sueldoBruto);
            
            if(setearDatos == false){ //si retorna FALSE indica que TODOS los datos fueron ingresados correctamente
                
                //llama al metodo validar que el DNI no exista en la BD
                String sql = "SELECT dni FROM Empleados WHERE dni = '" + dni + "'and legajo <>'" + legajo + "'";

                boolean validarExistDNI = emple.validarDNIExist(dni,sql, legajo);
                
                if(validarExistDNI == false){// si el DNI ingresado no existe en la BD
                
                //llamo al metodo MODIFICAR EMPLEADOS de mi Clase Empleados
                boolean modifEmple = emple.modificarEmpleados(legajo, apellido, nombre, dni, fechaNac, genero, cargo, sueldoBruto);
                
                if(modifEmple == true){
                    limpiarCajas();
                    txtLegajo.setEnabled(true);
                    txtLegajo.requestFocus(true);
                    desactivarCajasBtn();

                    btnBuscar.setEnabled(true);
                    btnAgregar.setEnabled(true);
                }
              }  else {txtDNI2.setText("");
                       txtDNI2.requestFocus(true);
                      }
            } 
    	} catch(NumberFormatException ex){ //si lo que se ingresa x teclado no es un nro. genera error!
                JOptionPane.showMessageDialog(this, "Faltan datos de Cargar!!","Validación Carga de Datos",JOptionPane.ERROR_MESSAGE); 
                }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

     try{
        
     int resultado =  JOptionPane.showConfirmDialog(this, "Esta seguro que desea aliminar Empleado?", "Confirmacion",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
         
         if (resultado == JOptionPane.YES_OPTION){
                 
             Integer legajo = Integer.parseInt(txtLegajo.getText());
              boolean suprEmple = emple.eliminarEmpleado(legajo);
         
             if(suprEmple == true){
                        limpiarCajas();
                        txtLegajo.setEnabled(true);
                        txtLegajo.requestFocus(true);
                        desactivarCajasBtn();

                        btnBuscar.setEnabled(true);
                        btnAgregar.setEnabled(true);
             }
         }   
     }catch( Exception ex){
         
     }
    
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtLegajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLegajoKeyTyped
        //le asigna a la variable cada caraacter tipeado por el usuario
        char c = evt.getKeyChar();
        // pregunta si lo que se ingresa esta entre 0 y 9 - asi me aseguro que sean solo nros.
        if(c<'0'|| c>'9')
            // que le permita editar
            evt.consume();
    }//GEN-LAST:event_txtLegajoKeyTyped

    private void txtDNI2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNI2KeyTyped

    }//GEN-LAST:event_txtDNI2KeyTyped

    private void txtSueldoBrutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoBrutoKeyTyped

    }//GEN-LAST:event_txtSueldoBrutoKeyTyped

    private void txtDNI2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNI2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNI2FocusLost

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
          PantallaLogin verPantalla = new PantallaLogin();
        verPantalla.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnSalirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboCargo;
    private javax.swing.JCheckBox chkFemenino;
    private javax.swing.JCheckBox chkMasculino;
    private javax.swing.JCheckBox chkOtro;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblFondoEmple;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLegajo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSueldoBruto;
    private javax.swing.JLabel lblTituloEmpleado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JFormattedTextField txtDNI2;
    private javax.swing.JFormattedTextField txtFechaNac;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldoBruto;
    // End of variables declaration//GEN-END:variables
}
