
package TPI_Empleados;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.sql.Connection;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;


public class PantallaAltaUsuario extends javax.swing.JFrame {
    
      //Variables
    private Usuarios uss;
    private DatabaseConection c;

    //Constructor
    public PantallaAltaUsuario() {
        initComponents();
        
        //para que el formulario parezca en el centro
        this.setLocationRelativeTo(null);
        
       // desactiva el boton maximizar
        this.setResizable(false);
        
        //coloco un titulo al jFrame
         this.setTitle("Alta de Usuarios");
         
         uss = new Usuarios();

    }
    
    
    //Creo metodo que limpie cajas de texto
    public void limpiarCajas(){
     txtApellido.setText("");
     txtNombre.setText("");
     txtUsuario.setText("");
     txtPass.setText("");
     txtConfPass.setText("");
     cboCargo.setSelectedItem("**Seleccione Opción**");
     txtmail.setText("");
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtConfPass = new javax.swing.JPasswordField();
        cboCargo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblAsteriscoConfPass = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblAsteriscoApellido = new javax.swing.JLabel();
        lblAsteriscoNombre = new javax.swing.JLabel();
        lblAsteriscoEmail = new javax.swing.JLabel();
        lblAsteriscoPerfil = new javax.swing.JLabel();
        lblAsteriscoUsuario = new javax.swing.JLabel();
        lblAsteriscoPass = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Apellido:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 58, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("E-mail:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Perfil:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Usuario:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Pasword:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Repetir  Pasword:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 289, 160, -1));

        txtmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmailFocusLost(evt);
            }
        });
        jPanel2.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 213, 160, -1));

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 175, 160, -1));

        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 327, 160, -1));

        txtConfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfPassFocusLost(evt);
            }
        });
        txtConfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfPassActionPerformed(evt);
            }
        });
        jPanel2.add(txtConfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 365, 160, -1));

        cboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "**Seleccione Opción**", "Gerente", "Administración", "Contabilidad", "Recursos Humanos", "Secretaria", "Personal Cajero", "Personal Repositores", "Personal Limpieza", " " }));
        cboCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboCargoFocusLost(evt);
            }
        });
        jPanel2.add(cboCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 251, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REGISTER NOW");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 176, 56));

        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 137, 160, -1));

        lblAsteriscoConfPass.setText("*");
        jPanel2.add(lblAsteriscoConfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 30, 40));

        btnCancel.setBackground(new java.awt.Color(153, 0, 204));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 111, 30));

        btnSubmit.setBackground(new java.awt.Color(153, 0, 204));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("REGISTRAR");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 111, 30));

        lblAsteriscoApellido.setText("*");
        jPanel2.add(lblAsteriscoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 30, 20));

        lblAsteriscoNombre.setText("*");
        jPanel2.add(lblAsteriscoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 30, 20));

        lblAsteriscoEmail.setText("*");
        jPanel2.add(lblAsteriscoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 30, 30));

        lblAsteriscoPerfil.setText("*");
        jPanel2.add(lblAsteriscoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 30, 40));

        lblAsteriscoUsuario.setText("*");
        jPanel2.add(lblAsteriscoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 30, 40));

        lblAsteriscoPass.setText("*");
        jPanel2.add(lblAsteriscoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 30, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 330, 510));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUsuario.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
       PantallaInicial verPantallaInicial = new PantallaInicial();
       verPantallaInicial.setVisible(true); 
       this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

         //capturo los valores de las cajas de texto
         String apellido = txtApellido.getText();
         String nombre = txtNombre.getText();
         String usuario = txtUsuario.getText();
         String pass = txtPass.getText();
         String confPass = txtConfPass.getText();
         String cargo =  cboCargo.getSelectedItem().toString();
         String mail = txtmail.getText();

         //llamo al metodo, para validar lo ingresado por el usuario
         //boolean validarCajas = uss.validarCajasTexto(apellido, nombre, mail, cargo, usuario, pass, confPass);
           boolean validarCajas = uss.validarCajasTexto2(apellido, nombre, mail, cargo, usuario, pass, confPass);
         // si NO genera error
         if (validarCajas == false){
             boolean validarEmail =  uss.validarMail(mail);
            // pregunto si es =false, quiere decir que es correcto el mail ingresado
               if(validarEmail == false){
                   if(pass.equals(confPass)){//si las contraseñas son iguales                                 
                       //llamo al metodo insertarUusario
                        try{
                              boolean  insertarUss = uss.insertarUsuario(apellido, nombre, usuario, pass, cargo, mail);
                              if( insertarUss == false){
                                   this.limpiarCajas();
                              }

                        } catch (Exception x){
                                Logger.getLogger(PantallaAltaUsuario.class.getName()).log(Level.SEVERE, null, x);}
                     } else{JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden!!","Validación Carga de Datos",JOptionPane.ERROR_MESSAGE); 
                             txtPass.requestFocus(true);
                             txtConfPass.setText("");
                             txtPass.setText("");
                           } 
                   } else {txtmail.requestFocus(true);}
         }//else System.out.println("Hubo un error en la validacion de cajas, no se pudo grabar!");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtConfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfPassActionPerformed

    }//GEN-LAST:event_txtConfPassActionPerformed

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        
        if(txtApellido.getText().trim().equals("")){
           this.lblAsteriscoApellido.setForeground(Color.red);
        }else  this.lblAsteriscoApellido.setForeground(Color.black);
        
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
           if(txtNombre.getText().trim().equals("")){
           this.lblAsteriscoNombre.setForeground(Color.red);
        }else  this.lblAsteriscoNombre.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmailFocusLost
          if(txtmail.getText().trim().equals("")){
           this.lblAsteriscoEmail.setForeground(Color.red);
        }else  this.lblAsteriscoEmail.setForeground(Color.black);
    }//GEN-LAST:event_txtmailFocusLost

    private void cboCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboCargoFocusLost
        
        if(cboCargo.getSelectedItem().toString().equals("**Seleccione Opción**")){
           this.lblAsteriscoPerfil.setForeground(Color.red);
        }else  this.lblAsteriscoPerfil.setForeground(Color.black);
        
    }//GEN-LAST:event_cboCargoFocusLost

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
          if(txtUsuario.getText().trim().equals("")){
           this.lblAsteriscoUsuario.setForeground(Color.red);
        }else  this.lblAsteriscoUsuario.setForeground(Color.black);
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
         if(txtPass.getText().trim().equals("")){
           this.lblAsteriscoPass.setForeground(Color.red);
        }else  this.lblAsteriscoPass.setForeground(Color.black);
    }//GEN-LAST:event_txtPassFocusLost

    private void txtConfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfPassFocusLost
         if(txtConfPass.getText().trim().equals("")){
           this.lblAsteriscoConfPass.setForeground(Color.red);
        }else  this.lblAsteriscoConfPass.setForeground(Color.black);
    }//GEN-LAST:event_txtConfPassFocusLost

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAsteriscoApellido;
    private javax.swing.JLabel lblAsteriscoConfPass;
    private javax.swing.JLabel lblAsteriscoEmail;
    private javax.swing.JLabel lblAsteriscoNombre;
    private javax.swing.JLabel lblAsteriscoPass;
    private javax.swing.JLabel lblAsteriscoPerfil;
    private javax.swing.JLabel lblAsteriscoUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtmail;
    // End of variables declaration//GEN-END:variables
}
